Import('env', 'envCython', 'arch')

# Create a special environment for params.cc with lower optimization
# to prevent OOM during compilation (params_keys.h has ~500 map entries)
env_params = env.Clone()
env_params['CCFLAGS'] = [f for f in env_params['CCFLAGS'] if f != '-O2'] + ['-O1']

common_libs = [
  env_params.Object('params.cc'),  # Compile with -O1 to reduce memory usage
  'swaglog.cc',
  'util.cc',
  'watchdog.cc',
  'ratekeeper.cc'
]

_common = env.Library('common', common_libs, LIBS="json11")

files = [
  'clutil.cc',
]

_gpucommon = env.Library('gpucommon', files)
Export('_common', '_gpucommon')

if GetOption('extras'):
  env.Program('tests/test_common',
              ['tests/test_runner.cc', 'tests/test_params.cc', 'tests/test_util.cc', 'tests/test_swaglog.cc'],
              LIBS=[_common, 'json11', 'zmq', 'pthread'])

# Cython bindings
params_python = envCython.Program('params_pyx.so', 'params_pyx.pyx', LIBS=envCython['LIBS'] + [_common, 'zmq', 'json11'])

SConscript([
  'transformations/SConscript',
])

Import('transformations_python')
common_python = [params_python, transformations_python]

Export('common_python')
